# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: YE WANG
email: "yewangfaith@gmail.com"
description: 王也的博客 | Ye Wang's Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://faithman.github.io" # the base hostname & protocol for your site
twitter_username: YeWang64874698
github_username:  faithman
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
# set highlight
highlighter: rouge

# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  syntax_highlighter: rouge

sharing :
  provider : false

# Setting for comments helper
comments :
  provider : disqus
  disqus :
    short_name : jekyllbootstrap
  livefyre :
    site_id : 123
  intensedebate :
    account : 123abc
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light
  duoshuo :
    short_name : jekyllbootstrap